export enum DEFAULT_MESSAGE_TYPE {
  CONNECTED = '__EASY_IFRAME_CONNECTED__',
  CONNECTING = '__EASY_IFRAME_CONNECTING__',
  MAIN_INIT = '__EASY_IFRAME_MAIN_INIT__',
  SUB_INIT = '__EASY_IFRAME_SUB_INIT__',
}
